# frozen_string_literal: true

require "securerandom"
require "time"
require "json"

module Clacky
  # Host-owned session state for an extension-provided agent runtime.
  class RuntimeSession
    class BusyError < StandardError; end
    class UnsupportedCapability < StandardError; end

    # Keeps the host-owned transcript readable when an extension that owns a
    # persisted runtime session is disabled, missing, or fails to load. It
    # deliberately preserves only the already-sanitized resume state and
    # refuses to execute new turns.
    class UnavailableRuntime
      def initialize(runtime_id:, persisted_state: nil, message: nil)
        @runtime_id = runtime_id.to_s
        @persisted_state = persisted_state.is_a?(Hash) ? persisted_state : {}
        @message = message || "Agent runtime '#{@runtime_id}' is unavailable"
      end

      def capabilities
        {}
      end

      def run(_input, generation:)
        raise UnsupportedCapability, @message
      end

      def dump_state
        deep_copy(@persisted_state)
      end

      def close
        nil
      end

      private def deep_copy(value)
        case value
        when Hash
          value.each_with_object({}) do |(key, item), copy|
            copy[deep_copy(key)] = deep_copy(item)
          end
        when Array
          value.map { |item| deep_copy(item) }
        else
          begin
            value.dup
          rescue TypeError
            value
          end
        end
      end
    end

    RuntimeInput = Struct.new(
      :content,
      :files,
      :reference_contexts,
      :display_text,
      :created_at,
      :references_display,
      keyword_init: true
    )

    attr_reader :session_id, :name, :history, :working_dir, :created_at,
      :total_tasks, :total_cost, :cost_source, :ui, :agent_profile, :source,
      :config, :latest_latency, :reasoning_effort, :todos
    attr_accessor :pinned, :project_id, :channel_info

    def self.from_session(runtime_factory:, config:, session_data:, ui:, profile:)
      runtime = value(session_data, :runtime) || {}
      new(
        runtime_id: value(runtime, :id),
        runtime_factory: runtime_factory,
        config: config,
        working_dir: value(session_data, :working_dir) || Dir.pwd,
        ui: ui,
        profile: profile,
        session_id: value(session_data, :session_id),
        source: (value(session_data, :source) || "manual").to_sym,
        persisted_state: value(runtime, :state),
        persisted_data: session_data
      )
    end

    def self.value(hash, key)
      return nil unless hash.is_a?(Hash)

      hash[key] || hash[key.to_s]
    end

    def initialize(runtime_id:, runtime_factory:, config:, working_dir:, ui:,
                   profile:, session_id:, source:, persisted_state: nil,
                   persisted_data: nil)
      @runtime_id = runtime_id.to_s
      raise ArgumentError, "runtime_id is required" if @runtime_id.empty?

      @config = config
      @working_dir = working_dir || Dir.pwd
      @ui = ui
      @agent_profile = profile
      @session_id = session_id
      @source = source.to_sym
      @name = ""
      @name_autogenerated = true
      @pinned = false
      @project_id = nil
      @channel_info = nil
      @created_at = Time.now.iso8601
      @history = MessageHistory.new
      @input_queue = []
      @input_mutex = Mutex.new
      @total_tasks = 0
      @total_cost = 0.0
      @cost_source = :provider
      @latest_latency = nil
      @reasoning_effort = nil
      @todos = []
      @generation_mutex = Mutex.new
      @current_generation = nil
      @assistant_buffers = {}
      @assistant_order = []
      @assistant_stream_seen = false
      @runtime_tool_calls = {}
      @completed_tool_calls = {}
      @runtime_tool_sequence = 0
      @closed = false

      restore_host_state(persisted_data) if persisted_data

      context = {
        session_id: @session_id,
        working_dir: @working_dir,
        permission_mode: permission_mode,
        default_model: @config.current_model &&
          @config.current_model["display_model"],
        ui: @ui,
        event_sink: method(:accept_runtime_event)
      }
      @runtime = runtime_factory.call(
        context: context,
        persisted_state: deep_copy(persisted_state)
      )
      refresh_effective_configuration
    end

    def runtime?
      true
    end

    def runtime_id
      @runtime_id
    end

    def capabilities
      value = @runtime.respond_to?(:capabilities) ? @runtime.capabilities : {}
      value.is_a?(Hash) ? value : {}
    end

    def capability?(name)
      capabilities[name.to_sym] == true || capabilities[name.to_s] == true
    end

    def permission_mode
      @config&.permission_mode&.to_s || ""
    end

    def reasoning_effort=(value)
      @reasoning_effort = value.to_s.strip
      @reasoning_effort = nil if @reasoning_effort.empty?
    end

    def current_model_info
      card = @config&.current_model || {}
      state = runtime_state
      model = state["model"] || card["display_model"] || "Runtime default"
      model_options = runtime_model_options
      {
        id: card["id"],
        model: model,
        base_url: nil,
        provider_id: card["provider_id"],
        runtime_id: @runtime_id,
        remark: card["remark"],
        card_model: card["display_model"],
        sub_model: model_options.include?(model) ? model : nil,
        sub_model_options: model_options
      }
    end

    def rename(new_name, automatic: false)
      was_empty = @name.empty?
      @name = new_name.to_s.strip
      @name_autogenerated = !!automatic ||
                            (was_empty && autogenerated_name?(@name))
    end

    def parse_skill_command(_input)
      { found: false }
    end

    def run(content, files: nil, reference_contexts: nil, display_text: nil,
            created_at: nil, references_display: nil)
      generation = Thread.current[:task_epoch] || next_local_generation
      started_at = nil
      begin_generation(generation)
      timestamp = created_at || Time.now.to_f
      @history.append(
        role: "user",
        content: content,
        display_text: display_text,
        created_at: timestamp,
        display_files: Array(files),
        display_references: Array(references_display)
      )

      input = RuntimeInput.new(
        content: content,
        files: Array(files),
        reference_contexts: Array(reference_contexts),
        display_text: display_text,
        created_at: timestamp,
        references_display: Array(references_display)
      )
      started_at = Time.now
      result = @runtime.run(input, generation: generation)
      result = {} unless result.is_a?(Hash)
      finalize_assistant_message(generation, result, started_at)
      @total_tasks += 1
      refresh_effective_configuration
      {
        stop_reason: result[:stop_reason] || result["stop_reason"],
        awaiting_user_feedback: !!(
          result[:awaiting_user_feedback] || result["awaiting_user_feedback"]
        )
      }
    rescue Clacky::AgentInterrupted, StandardError
      finalize_assistant_message(generation, {}, started_at) if started_at
      raise
    ensure
      complete_generation(generation) if generation
    end

    def begin_generation(generation)
      @generation_mutex.synchronize do
        @current_generation = generation.to_i
        @assistant_buffers = {}
        @assistant_order = []
        @assistant_stream_seen = false
        @runtime_tool_calls = {}
        @completed_tool_calls = {}
        @runtime_tool_sequence = 0
      end
      generation
    end

    def accept_runtime_event(generation, event)
      return false unless event.is_a?(Hash)

      event_type = (event[:type] || event["type"]).to_s
      case event_type
      when "assistant_delta"
        buffer_assistant_delta(generation, event)
      when "tool_call"
        record_tool_call(generation, event)
      when "tool_result"
        record_tool_result(generation, event)
      when "thought"
        show_runtime_progress(generation, event, progress_type: "thinking")
      when "warning"
        show_runtime_warning(generation, event)
      when "usage"
        apply_usage(generation, event)
      when "plan"
        apply_plan(generation, event)
      when "session_info"
        accept_runtime_title(generation, event)
      else
        accepted = current_generation?(generation)
        log_ignored_runtime_event(event_type, event) if accepted
        accepted
      end
    end

    def enqueue_input(content, **options)
      entry = { id: SecureRandom.uuid, content: content, options: options }
      @input_mutex.synchronize { @input_queue << entry }
      notify_input_queue
      entry[:id]
    end

    def pending_inputs
      @input_mutex.synchronize { deep_copy(@input_queue) }
    end

    def take_pending_input
      @input_mutex.synchronize { @input_queue.shift }
    end

    def edit_pending_input(id, content)
      updated = @input_mutex.synchronize do
        entry = @input_queue.find { |item| item[:id] == id }
        if entry
          entry[:content] = content
          entry[:options][:display_text] = content if entry[:options][:display_text]
          true
        end
      end
      notify_input_queue
      !!updated
    end

    def remove_pending_input(id)
      removed = @input_mutex.synchronize do
        index = @input_queue.index { |entry| entry[:id] == id }
        @input_queue.delete_at(index) if index
      end
      notify_input_queue
      removed
    end

    def restore_pending_input(entry)
      @input_mutex.synchronize do
        @input_queue.unshift(entry) unless @input_queue.any? do |item|
          item[:id] == entry[:id]
        end
      end
      notify_input_queue
      entry[:id]
    end

    def run_pending_input(entry)
      options = entry[:options].dup
      source = options.delete(:source) || :web
      steering = options.key?(:steering) ? options.delete(:steering) : true
      show_user_message = options.key?(:show_user_message) ?
        options.delete(:show_user_message) : true
      notify_input_queue
      if show_user_message && @ui&.respond_to?(:show_user_message)
        @ui.show_user_message(
          options[:display_text] || entry[:content],
          created_at: options[:created_at],
          files: options[:files] || [],
          source: source,
          steering: steering
        )
      end
      run(entry[:content], **options)
    end

    def cancel(reason:)
      return false unless @runtime.respond_to?(:cancel)

      @runtime.cancel(reason: reason)
    end

    def close
      return if @closed

      @closed = true
      @runtime.close if @runtime.respond_to?(:close)
    end

    def change_working_dir(_new_dir)
      raise UnsupportedCapability,
            "agent runtime does not support changing the working directory"
    end

    def fork_runtime_state
      raise UnsupportedCapability, "agent runtime sessions do not support fork"
    end

    def switch_model_by_id(id)
      current = @config&.current_model
      return true if current && current["id"].to_s == id.to_s

      false
    end

    def set_session_sub_model(model_name)
      unless capability?(:model_selection) && @runtime.respond_to?(:set_model)
        raise UnsupportedCapability,
              "agent runtime does not support model selection"
      end

      requested = model_name.to_s.strip
      if requested.empty?
        raise UnsupportedCapability,
              "runtime model selection requires an advertised model"
      end

      result = @runtime.set_model(requested)
      return false if result == false

      refresh_effective_configuration
      true
    end

    def to_session_data(status: :success, error_message: nil, raw_message: nil,
                        updated_at: nil)
      stats = {
        total_tasks: @total_tasks,
        total_iterations: 0,
        total_cost_usd: @total_cost.round(4),
        cost_source: @cost_source.to_s,
        last_status: status.to_s
      }
      stats[:last_error] = error_message if status == :error && error_message
      stats[:last_error_raw] = raw_message if status == :error && raw_message

      card = @config&.current_model || {}
      {
        session_id: @session_id,
        name: @name,
        name_autogenerated: @name_autogenerated,
        pinned: @pinned,
        created_at: @created_at,
        updated_at: iso8601(updated_at || Time.now),
        working_dir: @working_dir,
        source: @source.to_s,
        agent_profile: @agent_profile&.name.to_s,
        pending_inputs: pending_inputs,
        todos: @todos,
        config: {
          permission_mode: permission_mode,
          model_id: card["id"],
          provider_id: card["provider_id"]
        },
        runtime: {
          id: @runtime_id,
          version: 1,
          state: runtime_state
        },
        channel_info: @channel_info,
        project_id: @project_id,
        stats: stats,
        messages: @history.to_a
      }
    end

    def replay_history(target_ui, limit: 20, before: nil)
      visible = visible_history_messages
      if before
        visible = visible.select do |message|
          timestamp = self.class.value(message, :created_at)
          !timestamp || timestamp.to_f < before.to_f
        end
      end
      user_count = visible.count do |message|
        self.class.value(message, :role).to_s == "user"
      end
      has_more = user_count > limit
      if has_more
        allowed_users = 0
        visible = visible.reverse.take_while do |message|
          if self.class.value(message, :role).to_s == "user"
            allowed_users += 1
          end
          allowed_users <= limit
        end.reverse
      end

      visible.each { |message| replay_history_message(target_ui, message) }
      { has_more: has_more }
    end

    # The Web UI always requests cursor-window history, independently of Time
    # Machine. Runtime transcripts are append-only, so an index plus the user
    # timestamp is a stable, provider-neutral cursor across process restarts.
    def replay_history_window(target_ui, limit: 30, around: nil,
                              before_id: nil, after_id: nil)
      rounds, leading = runtime_history_rounds
      if rounds.empty?
        leading.each { |message| replay_history_message(target_ui, message) }
        return {
          has_more: false,
          has_after: false,
          before_cursor: nil,
          after_cursor: nil,
          round_ids: []
        }
      end

      anchor = around || before_id || after_id
      anchor_index = runtime_history_cursor_index(anchor, rounds) if anchor
      indexes = runtime_history_page_indexes(
        rounds.length,
        limit,
        around: around,
        before_id: before_id,
        after_id: after_id,
        anchor_index: anchor_index
      )
      indexes.each do |index|
        rounds[index][:messages].each do |message|
          replay_history_message(target_ui, message)
        end
      end

      first_index = indexes.first
      last_index = indexes.last
      ids = indexes.map { |index| rounds[index][:id] }
      {
        has_more: !!(first_index && first_index.positive?),
        has_after: !!(last_index && last_index < rounds.length - 1),
        before_cursor: ids.first,
        after_cursor: ids.last,
        round_ids: ids
      }
    end

    private def restore_host_state(data)
      @name = self.class.value(data, :name).to_s
      name_autogenerated = self.class.value(data, :name_autogenerated)
      @name_autogenerated = if name_autogenerated.nil?
                              autogenerated_name?(@name)
                            else
                              !!name_autogenerated
                            end
      @pinned = !!self.class.value(data, :pinned)
      @project_id = self.class.value(data, :project_id)
      @channel_info = self.class.value(data, :channel_info)
      @created_at = self.class.value(data, :created_at) || @created_at
      @history = MessageHistory.new(Array(self.class.value(data, :messages)))
      @input_queue = Array(self.class.value(data, :pending_inputs))
      @todos = Array(self.class.value(data, :todos))
      stats = self.class.value(data, :stats) || {}
      @total_tasks = self.class.value(stats, :total_tasks).to_i
      @total_cost = self.class.value(stats, :total_cost_usd).to_f
      source = self.class.value(stats, :cost_source)
      @cost_source = source.to_s.empty? ? :provider : source.to_sym
    end

    private def visible_history_messages
      @history.to_a.reject do |message|
        self.class.value(message, :system_injected) ||
          self.class.value(message, :role).to_s == "system"
      end
    end

    private def runtime_history_rounds
      rounds = []
      leading = []
      visible_history_messages.each do |message|
        if self.class.value(message, :role).to_s == "user"
          index = rounds.length
          rounds << {
            id: runtime_history_round_id(message, index),
            messages: [message]
          }
        elsif rounds.empty?
          leading << message
        else
          rounds.last[:messages] << message
        end
      end
      rounds.first[:messages] = leading + rounds.first[:messages] if rounds.any?
      [rounds, leading]
    end

    private def runtime_history_round_id(message, index)
      JSON.generate([
        "runtime",
        index,
        self.class.value(message, :created_at)
      ])
    end

    private def runtime_history_cursor_index(cursor, rounds)
      kind, index, created_at = JSON.parse(cursor.to_s)
      unless kind == "runtime" && index.is_a?(Integer) && index >= 0 &&
             index < rounds.length
        raise ArgumentError, "Invalid history location"
      end

      expected = JSON.parse(rounds[index][:id])
      unless created_at == expected[2]
        raise ArgumentError, "History location is no longer available"
      end

      index
    rescue JSON::ParserError, TypeError
      raise ArgumentError, "Invalid history location"
    end

    private def runtime_history_page_indexes(count, limit, around:, before_id:,
                                             after_id:, anchor_index:)
      page_limit = [limit.to_i, 1].max
      if around
        first = anchor_index
        last = [first + page_limit - 1, count - 1].min
      elsif after_id
        first = anchor_index + 1
        last = [first + page_limit - 1, count - 1].min
      else
        last = before_id ? anchor_index - 1 : count - 1
        first = [last - page_limit + 1, 0].max
      end
      return [] if first.nil? || last.nil? || first > last || first >= count || last.negative?

      (first..last).to_a
    end

    private def replay_history_message(target_ui, message)
      role = self.class.value(message, :role).to_s
      case role
      when "user"
        target_ui.show_user_message(
          self.class.value(message, :display_text) ||
            self.class.value(message, :content),
          created_at: self.class.value(message, :created_at),
          files: Array(self.class.value(message, :display_files)),
          references: Array(self.class.value(message, :display_references)),
          source: :history
        )
      when "assistant"
        content = self.class.value(message, :content).to_s
        unless content.strip.empty?
          target_ui.show_assistant_message(
            content,
            files: [],
            created_at: self.class.value(message, :created_at)
          )
        end
        Array(self.class.value(message, :tool_calls)).each do |tool_call|
          replay_tool_call(target_ui, tool_call)
        end
      when "tool"
        replay_tool_result(target_ui, message)
      end
    end

    private def buffer_assistant_delta(generation, event)
      message_id = (event[:message_id] || event["message_id"] || "assistant").to_s
      content = (event[:content] || event["content"]).to_s
      accepted = mutate_current_generation(generation) do
        next if content.empty?

        unless @assistant_buffers.key?(message_id)
          @assistant_buffers[message_id] = String.new
          @assistant_order << message_id
        end
        @assistant_buffers[message_id] << content
        @assistant_stream_seen = true
      end
      if accepted && !content.empty? && @ui&.respond_to?(:show_assistant_delta)
        with_runtime_generation(generation) do
          @ui.show_assistant_delta(message_id, content)
        end
      end
      accepted
    end

    private def finalize_assistant_message(generation, result, started_at)
      payload = @generation_mutex.synchronize do
        next unless @current_generation && @current_generation.to_i == generation.to_i

        latency = { total_ms: ((Time.now - started_at) * 1000).round }
        @latest_latency = latency
        take_assistant_payload_locked(
          fallback_text: result[:assistant_text] || result["assistant_text"],
          latency: latency
        )
      end
      return unless payload

      deliver_assistant_payload(generation, payload)
    end

    private def record_tool_call(generation, event)
      name = (event[:name] || event["name"] || "tool").to_s
      input = deep_copy(event[:input] || event["input"] || {})
      id = nil
      assistant_payload = nil
      accepted = mutate_current_generation(generation) do
        assistant_payload = take_assistant_payload_locked
        id = runtime_tool_call_id_locked(event)
        @runtime_tool_calls[id] = { id: id, name: name, input: input }
      end
      return false unless accepted

      deliver_assistant_payload(generation, assistant_payload) if assistant_payload
      with_runtime_generation(generation) do
        if @ui&.respond_to?(:show_keyed_tool_call)
          @ui.show_keyed_tool_call(name, input, tool_call_id: id)
        else
          @ui&.show_tool_call(name, input)
        end
      end
      true
    end

    private def take_assistant_payload_locked(fallback_text: nil, latency: nil)
      combined = @assistant_order.map { |id| @assistant_buffers[id] }.join
      if combined.empty? && !@assistant_stream_seen
        combined = fallback_text.to_s
      end
      return nil if combined.strip.empty?

      ids = @assistant_order.dup
      ids = ["assistant"] if ids.empty?
      timestamp = Time.now.to_f
      message = {
        role: "assistant",
        content: combined,
        created_at: timestamp
      }
      message[:latency] = latency if latency
      @history.append(message)
      @assistant_buffers = {}
      @assistant_order = []
      [combined, ids.first, ids, timestamp]
    end

    private def deliver_assistant_payload(generation, payload)
      text, message_id, message_ids, timestamp = payload
      with_runtime_generation(generation) do
        if @ui&.respond_to?(:finish_assistant_stream)
          @ui.finish_assistant_stream(
            message_id,
            text,
            files: [],
            created_at: timestamp,
            message_ids: message_ids
          )
        else
          @ui&.show_assistant_message(text, files: [], created_at: timestamp)
        end
      end
    end

    private def record_tool_result(generation, event)
      result = event.key?(:result) ? event[:result] : event["result"]
      status = self.class.value(event, :status).to_s
      status = nil if status.empty?
      exit_code = self.class.value(event, :exit_code)
      id = nil
      accepted = mutate_current_generation(generation) do
        id = runtime_tool_call_id_locked(event)
        persist_tool_exchange(
          id,
          result,
          status: status,
          exit_code: exit_code
        ) unless @completed_tool_calls[id]
        @completed_tool_calls[id] = true
      end
      return false unless accepted

      with_runtime_generation(generation) do
        if @ui&.respond_to?(:show_keyed_tool_result)
          @ui.show_keyed_tool_result(
            result,
            tool_call_id: id,
            status: status,
            exit_code: exit_code
          )
        else
          @ui&.show_tool_result(result)
        end
      end
      true
    end

    private def persist_tool_exchange(id, result, status: nil, exit_code: nil)
      call = @runtime_tool_calls[id]
      if call
        @history.append(
          role: "assistant",
          content: nil,
          tool_calls: [{
            id: id,
            type: "function",
            function: {
              name: call[:name],
              arguments: serialized_tool_value(call[:input])
            }
          }],
          created_at: Time.now.to_f
        )
      end
      message = {
        role: "tool",
        tool_call_id: id,
        content: serialized_tool_result(result),
        created_at: Time.now.to_f
      }
      message[:runtime_tool_status] = status if status
      message[:runtime_exit_code] = exit_code unless exit_code.nil?
      @history.append(message)
    end

    private def runtime_tool_call_id_locked(event)
      id = (event[:tool_call_id] || event["tool_call_id"]).to_s
      return id unless id.empty?

      @runtime_tool_sequence += 1
      "runtime-tool-#{@runtime_tool_sequence}"
    end

    private def serialized_tool_value(value)
      return value if value.is_a?(String)

      JSON.generate(value)
    rescue JSON::GeneratorError
      value.to_s
    end

    private def serialized_tool_result(result)
      result.is_a?(String) ? result : serialized_tool_value(result)
    end

    private def replay_tool_call(target_ui, tool_call)
      return unless tool_call.is_a?(Hash)

      id = self.class.value(tool_call, :id).to_s
      function = self.class.value(tool_call, :function) || {}
      name = self.class.value(tool_call, :name) || self.class.value(function, :name) || "tool"
      raw_arguments = self.class.value(tool_call, :arguments) ||
                      self.class.value(function, :arguments) || {}
      arguments = parse_tool_arguments(raw_arguments)
      if target_ui.respond_to?(:show_keyed_tool_call)
        target_ui.show_keyed_tool_call(name, arguments, tool_call_id: id)
      else
        target_ui.show_tool_call(name, arguments)
      end
    end

    private def replay_tool_result(target_ui, message)
      id = self.class.value(message, :tool_call_id).to_s
      result = self.class.value(message, :content).to_s
      status = self.class.value(message, :runtime_tool_status)
      exit_code = self.class.value(message, :runtime_exit_code)
      if target_ui.respond_to?(:show_keyed_tool_result)
        target_ui.show_keyed_tool_result(
          result,
          tool_call_id: id,
          status: status,
          exit_code: exit_code
        )
      else
        target_ui.show_tool_result(result)
      end
    end

    private def parse_tool_arguments(arguments)
      return arguments unless arguments.is_a?(String)

      JSON.parse(arguments)
    rescue JSON::ParserError
      arguments
    end

    private def accept_runtime_title(generation, event)
      title = (event[:title] || event["title"]).to_s.strip
      renamed = false
      accepted = mutate_current_generation(generation) do
        next if title.empty? || !@name_autogenerated

        rename(title, automatic: true)
        renamed = true
      end
      if accepted && renamed && @ui&.respond_to?(:emit)
        with_runtime_generation(generation) do
          @ui.emit("session_renamed", session_id: @session_id, name: title)
        end
      end
      accepted
    end

    private def log_ignored_runtime_event(event_type, event)
      provider_event_type = event[:session_update] || event["session_update"]
      Clacky::Logger.debug(
        "runtime.event_ignored",
        runtime_id: @runtime_id,
        event_type: provider_event_type.to_s.empty? ? event_type : provider_event_type.to_s
      ) if defined?(Clacky::Logger)
    end

    private def autogenerated_name?(value)
      value.to_s.empty? || value.to_s.match?(/\ASession \d+\z/)
    end

    private def apply_usage(generation, event)
      token_data, usd_cost = normalize_usage_event(event)
      accepted = mutate_current_generation(generation) do
        @total_cost = usd_cost if usd_cost
      end
      if accepted && @ui&.respond_to?(:show_token_usage)
        with_runtime_generation(generation) { @ui.show_token_usage(token_data) }
      end
      accepted
    end

    private def normalize_usage_event(event)
      payload = {}
      %w[
        used size prompt_tokens completion_tokens cache_read cache_write
        total_tokens delta_tokens thought_tokens
      ].each do |key|
        value = self.class.value(event, key.to_sym)
        payload[key.to_sym] = deep_copy(value) unless value.nil?
      end

      raw_cost = self.class.value(event, :cost)
      raw_cost = self.class.value(event, :cost_usd) if raw_cost.nil?
      amount, currency = runtime_cost(raw_cost)
      if raw_cost.is_a?(Hash)
        payload[:cost_currency] = currency unless currency.empty?
        if currency.casecmp("USD").zero? && amount
          payload[:cost] = amount
          payload[:cost_source] = "provider"
        elsif amount
          payload[:cost_amount] = amount
        end
      elsif amount
        payload[:cost] = amount
        source = self.class.value(event, :cost_source).to_s
        payload[:cost_source] = source.empty? ? "provider" : source
      end

      usd_cost = if raw_cost.is_a?(Hash)
                   amount if currency.casecmp("USD").zero?
                 else
                   amount
                 end
      [payload, usd_cost]
    end

    private def runtime_cost(raw_cost)
      if raw_cost.is_a?(Hash)
        amount = self.class.value(raw_cost, :amount)
        currency = self.class.value(raw_cost, :currency).to_s
        [finite_number(amount), currency]
      else
        [finite_number(raw_cost), ""]
      end
    end

    private def finite_number(value)
      return nil if value.nil?

      number = Float(value)
      number.finite? ? number : nil
    rescue ArgumentError, TypeError
      nil
    end

    private def apply_plan(generation, event)
      entries = Array(event[:entries] || event["entries"])
      content = (event[:content] || event["content"]).to_s
      todos = nil
      accepted = mutate_current_generation(generation) do
        unless entries.empty?
          @todos = deep_copy(entries)
          todos = deep_copy(@todos)
        end
      end
      return false unless accepted

      with_runtime_generation(generation) do
        @ui.update_todos(todos) if todos && @ui&.respond_to?(:update_todos)
        if !content.empty? && @ui&.respond_to?(:show_progress)
          @ui.show_progress(content, progress_type: "plan")
        end
      end
      true
    end

    private def show_runtime_progress(generation, event, progress_type:)
      content = event[:content] || event["content"]
      accepted = current_generation?(generation)
      if accepted && @ui&.respond_to?(:show_progress)
        with_runtime_generation(generation) do
          @ui.show_progress(content, progress_type: progress_type)
        end
      end
      accepted
    end

    private def show_runtime_warning(generation, event)
      content = (event[:content] || event["content"] ||
                 event[:message] || event["message"]).to_s.strip
      accepted = current_generation?(generation)
      if accepted && !content.empty? && @ui&.respond_to?(:show_warning)
        with_runtime_generation(generation) { @ui.show_warning(content) }
      end
      accepted
    end

    private def current_generation?(generation)
      @generation_mutex.synchronize do
        @current_generation && @current_generation.to_i == generation.to_i
      end
    end

    private def complete_generation(generation)
      @generation_mutex.synchronize do
        if @current_generation &&
           @current_generation.to_i == generation.to_i
          @current_generation = nil
        end
      end
    end

    private def mutate_current_generation(generation)
      @generation_mutex.synchronize do
        next false unless @current_generation &&
                          @current_generation.to_i == generation.to_i

        yield
        true
      end
    end

    private def with_runtime_generation(generation)
      previous = Thread.current[:task_epoch]
      Thread.current[:task_epoch] = generation.to_i
      yield
    ensure
      Thread.current[:task_epoch] = previous
    end

    private def refresh_effective_configuration
      state = runtime_state
      self.reasoning_effort = state["reasoning_effort"] if state["reasoning_effort"]
    end

    private def runtime_model_options
      return [] unless capability?(:model_selection)
      return [] unless @runtime.respond_to?(:model_options)

      Array(@runtime.model_options).filter_map do |model|
        value = model.to_s.strip
        value unless value.empty?
      end.uniq
    rescue StandardError
      []
    end

    private def runtime_state
      state = @runtime.respond_to?(:dump_state) ? @runtime.dump_state : {}
      state.is_a?(Hash) ? deep_copy(state) : {}
    end

    private def notify_input_queue
      @ui&.show_input_queue(pending_inputs) if @ui&.respond_to?(:show_input_queue)
    end

    private def next_local_generation
      @generation_mutex.synchronize { @current_generation.to_i + 1 }
    end

    private def iso8601(value)
      value.is_a?(String) ? value : value.iso8601
    end

    private def deep_copy(value)
      case value
      when Hash
        value.each_with_object({}) do |(key, item), copy|
          copy[deep_copy(key)] = deep_copy(item)
        end
      when Array
        value.map { |item| deep_copy(item) }
      else
        begin
          value.dup
        rescue TypeError
          value
        end
      end
    end
  end
end
